### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by ozanilbey** [phonetworks/graphjs#100]
- [ ] Implement anonymous comments (without html attributes)
- [x] Fix overflow problem on box component corners
- [x] Fix button on group-card (displays "...")
- [x] Create private-content from the ground up (remove this: 
<img width="268" alt="screen shot 2018-10-27 at 11 34 15 am" src="https://user-images.githubusercontent.com/3929181/47601640-65dfd300-d9dc-11e8-8c13-4f4ae6c10aaa.png">)
- [x] Fix star-button (fails on action)
- [ ] ~~Create missing show functions (showGroupList, showProfileList, showPrivateContent)~~
- [x] Fix Activity section on profile (doesn't work at all)
- [x] Check all loading states
- [x] Check all mobile views
- [x] Check all dark versions
- [x] Add max/min width/height options to Private Content (?)

**Comment by esokullu** [comment]
Private- content from ground up? I think essentially we need to fix the placeholder. What else do you see as problematic?

**Comment by ozanilbey** [comment]
Private content can be anything: image, video etc. but the tag displays a text content. I think I have a better solution for this: We can show anything put inside our <graphjs-private-content></graphjs-private-content> tag. The users don't have to put their content on our server this way (which is also problematic I think).

**Comment by esokullu** [comment]
you mean you will encrypt the content? because it shouldn't show as plain html.

**Comment by ozanilbey** [comment]
I will not encrypt the content, I will hide the html content using filters. It’s the common practice. If you want to keep it this way, I will only change the container style.

**Comment by ozanilbey** [comment]
Closing this one.
