### ISSUE TITLE
Improvement to-do

### ISSUE THREAD

**Issue by ozanilbey** [phonetworks/graphjs#195]
These items are needed to be done before v2.0 to make it better, cooler. We can comment on this issue with related visuals, code, anything necessary.

- [ ] Test all the components
- [ ] Test all the functions (including display functions)
- [ ] Test theme-ing (also dark theme for all the components)
- [ ] Test all the browser warnings
- [ ] Test mobile views (for all components & use cases)
- [ ] Test language options
- [ ] Test all the wording

**Comment by lokodevil** [comment]
[BLOG] when a new blog post is published it's automatically added to the end of the list. Logically and aesthetically when we don't have the function to display them in a certain order yet, will be better to have the latest blog put at the top of the blog list

**Comment by ozanilbey** [comment]
Feed components need to be tested after Thursday. Actually, we can leave it to the end.

**Comment by lokodevil** [comment]
[FORUM] `<graphjs-forum-thread>` can't be processed. Behavior as below: 
![image](https://user-images.githubusercontent.com/21268944/55455399-af78bd80-560d-11e9-8bb6-a6980a25f186.png)
Console showed an error with the language property:
![image](https://user-images.githubusercontent.com/21268944/55455435-d0411300-560d-11e9-8fc1-43f45c809728.png)
