### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by ozanilbey** [phonetworks/graphjs#69]
- [x] Edit comment/reply
- [x] Make Card components clickable (full body)
- [ ] Make color.less dynamically read and executed (instead of renderColor.js)
- [x] Separate Docs and Graph.js [CANCELLED]
- [x] Add a landing page (to Docs)
- [ ] Add informative texts (to Docs) [CANCELLED]
- [ ] Add a description to clarify init function (to Docs) [CANCELLED]
- [ ] Add color picker to create instant theme updates (to Docs) [CANCELLED]
- [x] Update graphjs.com (with @esokullu) [CANCELLED]
- [ ] Update repository readme file (with @esokullu)
- [ ] Feed paginated components with given number of items (with @esokullu)
- [ ] Add lazy-loading to Comments and Forum List components (with @esokullu)
- [x] Fix web page "title" informations used in Star List component (@esokullu)
- [ ] Clarify "show" and "to" options on Alert component [CANCELLED]
- [ ] Handle errors after server responds (remaining cases)
- [x] Test & fix bugs from scratch
- [x] Check deleteForumPost call for bugs
- [x] Check Messages component for bugs
- [ ] Add more image hosting services (?) [CANCELLED]
