### ISSUE TITLE
v1 To-do

### ISSUE THREAD

**Issue by ozanilbey** [phonetworks/graphjs#70]
- [x] Show Comments publicly
- [x] Add Contact component (similar to Messages Composer)
- [x] Add Testimonials component (similar to Comments, with rating)
- [ ] Create dashboard to create a new Graph.js user (color selection, theme, selection, url selection, anonymity preferences, moderation preferences, selecting what module(s) to use, subscription settings, cancellation, and data export) [CANCELLED]
- [x] Separate Docs from the library
- [x] Update Graph.js web site with better visuals, links to relevant parts in the Code, links to Docs, Dashboard, Authentication from the header [CANCELLED]
- [ ] Create moderation within Feedback component
- [ ] Create moderation for Feedback component on Dashboard (?)
- [x] Create dark version of Feedback component (after it is finalized)
- [x] Remove maximum character limit for emails on Auth: Register and Auth: Login
- [x] Change email regex to a simpler one

**Comment by ozanilbey** [comment]
@esokullu, FYI.

**Comment by ozanilbey** [comment]
Handled contact within Messages Composer. It looks like the right thing to do. User needs to add anonymity="true" to the component. @esokullu, you can tweak sendMessage call to accept anonymous messages or you can create a new call named sendAnonymousMessage(to, message). It will start working when the call is ready.

**Comment by esokullu** [comment]
OK can you commit/push this piece. It's better if you do that gradullay feature by feature, so it gives me time to review and make sure it's okay. Thanks,

**Comment by ozanilbey** [comment]
Email regex: /^[^\s@]+@[^\s@]+\.[^\s@]+$/
